/** \file

\author Pablo Haramburu
Copyright: 
	Copyright (C)2010 Pablo Haramburu.
License: 
	This file is part of mundial2010.

	mundial2010 is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	mundial2010 is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with mundial2010.  If not, see <http://www.gnu.org/licenses/>.
*/

// Generated by DialogBlocks (unregistered), 31/05/2010 13:18:00

#ifndef _MAINDIALOG_H_
#define _MAINDIALOG_H_


/*!
 * Includes
 */

#include "AppModel.h"

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MAINDIALOG 10000
#define ID_ADD_GOALKEEPER_BUTTON 10001
#define ID_GOALKEEPERS_LISTBOX 10002
#define ID_ADD_TESTFILE_BUTTON 10003
#define ID_TESTSFILES_LISTBOX 10004
#define ID_RUN_TESTS_BUTTON 10005
#define SYMBOL_MAINDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxMINIMIZE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_MAINDIALOG_TITLE wxGetTranslation(wxString(wxT("M")) + (wxChar) 0x00E9 + wxT("todos Num") + (wxChar) 0x00E9 + wxT("ricos 2010c1 - TP3 - Probador"))
#define SYMBOL_MAINDIALOG_IDNAME ID_MAINDIALOG
#define SYMBOL_MAINDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_MAINDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * MainDialog class declaration
 */

class MainDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( MainDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    MainDialog();
    MainDialog( wxWindow* parent, wxWindowID id = SYMBOL_MAINDIALOG_IDNAME, const wxString& caption = SYMBOL_MAINDIALOG_TITLE, const wxPoint& pos = SYMBOL_MAINDIALOG_POSITION, const wxSize& size = SYMBOL_MAINDIALOG_SIZE, long style = SYMBOL_MAINDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MAINDIALOG_IDNAME, const wxString& caption = SYMBOL_MAINDIALOG_TITLE, const wxPoint& pos = SYMBOL_MAINDIALOG_POSITION, const wxSize& size = SYMBOL_MAINDIALOG_SIZE, long style = SYMBOL_MAINDIALOG_STYLE );

    /// Destructor
    ~MainDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin MainDialog event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ADD_GOALKEEPER_BUTTON
    void OnAddGoalkeeperButtonClick( wxCommandEvent& event );

    /// wxEVT_KEY_DOWN event handler for ID_GOALKEEPERS_LISTBOX
    void OnGoalkeepersListboxKeyDown( wxKeyEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ADD_TESTFILE_BUTTON
    void OnAddTestfileButtonClick( wxCommandEvent& event );

    /// wxEVT_KEY_DOWN event handler for ID_TESTSFILES_LISTBOX
    void OnTestsfilesListboxKeyDown( wxKeyEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_RUN_TESTS_BUTTON
    void OnRunTestsButtonClick( wxCommandEvent& event );

    /// wxEVT_UPDATE_UI event handler for ID_RUN_TESTS_BUTTON
    void OnRunTestsButtonUpdate( wxUpdateUIEvent& event );

////@end MainDialog event handler declarations

////@begin MainDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end MainDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin MainDialog member variables
    wxListBox* m_goalkeepers;
    wxListBox* m_testfiles;
////@end MainDialog member variables
	wxCheckBox * m_showAnimation;
private:
	AppModel m_model;
};

#endif
    // _MAINDIALOG_H_
