/** \file

\author Pablo Haramburu
Copyright: 
	Copyright (C)2010 Pablo Haramburu.
License: 
	This file is part of mundial2010.

	mundial2010 is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	mundial2010 is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with mundial2010.  If not, see <http://www.gnu.org/licenses/>.
*/

// Generated by DialogBlocks (unregistered), 01/06/2010 01:49:44

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "TestResultsDialog.h"

////@begin XPM images
////@end XPM images


/*!
 * TestResultsDialog type definition
 */

IMPLEMENT_DYNAMIC_CLASS( TestResultsDialog, wxDialog )


/*!
 * TestResultsDialog event table definition
 */

BEGIN_EVENT_TABLE( TestResultsDialog, wxDialog )

////@begin TestResultsDialog event table entries
////@end TestResultsDialog event table entries

END_EVENT_TABLE()


/*!
 * TestResultsDialog constructors
 */

TestResultsDialog::TestResultsDialog()
{
    Init();
}

TestResultsDialog::TestResultsDialog( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}


/*!
 * TestResultsDialog creator
 */

bool TestResultsDialog::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin TestResultsDialog creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end TestResultsDialog creation
    return true;
}


/*!
 * TestResultsDialog destructor
 */

TestResultsDialog::~TestResultsDialog()
{
////@begin TestResultsDialog destruction
////@end TestResultsDialog destruction
}


/*!
 * Member initialisation
 */

void TestResultsDialog::Init()
{
////@begin TestResultsDialog member initialisation
    m_results = NULL;
    m_summary = NULL;
    m_cancelBtn = NULL;
////@end TestResultsDialog member initialisation
}


/*!
 * Control creation for TestResultsDialog
 */

void TestResultsDialog::CreateControls()
{    
////@begin TestResultsDialog content construction
    // Generated by DialogBlocks, 01/06/2010 04:20:21 (unregistered)

    TestResultsDialog* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    m_results = new wxListCtrl( itemDialog1, ID_LISTCTRL1, wxDefaultPosition, wxSize(300, 100), wxLC_REPORT );
    itemBoxSizer2->Add(m_results, 1, wxGROW|wxALL|wxFIXED_MINSIZE, 5);

    m_summary = new wxListCtrl( itemDialog1, ID_LISTCTRL2, wxDefaultPosition, wxSize(100, 100), wxLC_REPORT );
    itemBoxSizer2->Add(m_summary, 0, wxGROW|wxALL, 5);

    m_cancelBtn = new wxButton( itemDialog1, wxID_CANCEL, _("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer2->Add(m_cancelBtn, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

////@end TestResultsDialog content construction

	m_results->InsertColumn(0,_("Arquero"));
	m_results->InsertColumn(1,_("Test"));
	m_results->InsertColumn(2,_("Resultado"));
	m_summary->InsertColumn(0,_("Arquero"));
	m_summary->InsertColumn(1,_("Atajo"));
	m_summary->InsertColumn(2,_("de (tiros)"));
}


/*!
 * Should we show tooltips?
 */

bool TestResultsDialog::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap TestResultsDialog::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin TestResultsDialog bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end TestResultsDialog bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon TestResultsDialog::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin TestResultsDialog icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end TestResultsDialog icon retrieval
}
