all: informe.pdf

informe.pdf: informe.tex resultados_ej1_m1.tex resultados_ej1_m2.tex resultados_ej1_m3.tex resultados_ej2_m1.tex resultados_ej2_m2.tex resultados_misil.tex resultados_bomba.tex resultados_ej1_error.tex
	pdflatex informe.tex && pdflatex informe.tex
